services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: no
    ports:
      - "3001:3001"
    networks:
      - app_network
    environment:
      - NODE_ENV=production

  auth_service:
    container_name: auth_service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    restart: no
    networks:
      - app_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis
      - NODE_ENV=production
      - AUTH_DATABASE_URL=postgres://auth_user:auth_pass@auth_db:5432/auth_db
    depends_on:
      - auth_db
      - redis
    volumes:
      - ./keys:/app/keys:z

  todo-service:
    container_name: todo_service
    build:
      context: .
      dockerfile: ./apps/todo-service/Dockerfile
    networks:
      - app_network
    environment:
      - TODO_DATABASE_URL=mongodb://todo_user:todo_pass@todo_db:27017/todo_db?authSource=admin
      - NODE_ENV=production
      - QUEUE_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
    depends_on:
      - todo_db
      - rabbitmq

  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    ports:
      - "4173:4173"
    networks:
      - app_network

  auth_db:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - app_network

  todo_db:
    image: mongo:latest
    container_name: todo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo_user
      MONGO_INITDB_ROOT_PASSWORD: todo_pass
      MONGO_INITDB_DATABASE: todo_db
    ports:
      - "27017:27017"
    volumes:
      - todo_db_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app_network
    command: >
      redis-server
      --requirepass redis
      --appendonly yes
      --protected-mode no

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  auth_db_data:
  todo_db_data:
  redis_data:
  rabbitmq_data:
